
function adc_preproc_core_config(this_block)

  % Revision History:
  %
  %   04-Sep-2014  (10:57 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/jack/work/ami_correlator/ami/ami_correlator/adc_preproc_core.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('adc_preproc_core');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;

  this_block.addSimulinkInport('acc_len');
  this_block.addSimulinkInport('ns_invert');
  this_block.addSimulinkInport('inv_en');
  this_block.addSimulinkInport('ps_invert');
  this_block.addSimulinkInport('noise_en');
  this_block.addSimulinkInport('noise_seed');
  this_block.addSimulinkInport('seed_load');
  this_block.addSimulinkInport('i0');
  this_block.addSimulinkInport('i1');
  this_block.addSimulinkInport('i2');
  this_block.addSimulinkInport('i3');
  this_block.addSimulinkInport('i4');
  this_block.addSimulinkInport('i5');
  this_block.addSimulinkInport('i6');
  this_block.addSimulinkInport('i7');
  this_block.addSimulinkInport('i8');
  this_block.addSimulinkInport('i9');
  this_block.addSimulinkInport('i10');
  this_block.addSimulinkInport('i11');
  this_block.addSimulinkInport('i12');
  this_block.addSimulinkInport('i13');
  this_block.addSimulinkInport('i14');
  this_block.addSimulinkInport('i15');
  this_block.addSimulinkInport('sync');

  this_block.addSimulinkOutport('dout');
  this_block.addSimulinkOutport('sync_out');
  this_block.addSimulinkOutport('pow_sum');

  dout_port = this_block.port('dout');
  dout_port.setType('UFix_128_0');
  pow_sum_port = this_block.port('pow_sum');
  pow_sum_port.setType('UFix_64_0');
  sync_out_port = this_block.port('sync_out');
  sync_out_port.setType('Bool');
  sync_out_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('i0').width ~= 8);
      this_block.setError('Input data type for port "i0" must have width=8.');
    end

    if (this_block.port('i1').width ~= 8);
      this_block.setError('Input data type for port "i1" must have width=8.');
    end

    if (this_block.port('i10').width ~= 8);
      this_block.setError('Input data type for port "i10" must have width=8.');
    end

    if (this_block.port('i11').width ~= 8);
      this_block.setError('Input data type for port "i11" must have width=8.');
    end

    if (this_block.port('i12').width ~= 8);
      this_block.setError('Input data type for port "i12" must have width=8.');
    end

    if (this_block.port('i13').width ~= 8);
      this_block.setError('Input data type for port "i13" must have width=8.');
    end

    if (this_block.port('i14').width ~= 8);
      this_block.setError('Input data type for port "i14" must have width=8.');
    end

    if (this_block.port('i15').width ~= 8);
      this_block.setError('Input data type for port "i15" must have width=8.');
    end

    if (this_block.port('i2').width ~= 8);
      this_block.setError('Input data type for port "i2" must have width=8.');
    end

    if (this_block.port('i3').width ~= 8);
      this_block.setError('Input data type for port "i3" must have width=8.');
    end

    if (this_block.port('i4').width ~= 8);
      this_block.setError('Input data type for port "i4" must have width=8.');
    end

    if (this_block.port('i5').width ~= 8);
      this_block.setError('Input data type for port "i5" must have width=8.');
    end

    if (this_block.port('i6').width ~= 8);
      this_block.setError('Input data type for port "i6" must have width=8.');
    end

    if (this_block.port('i7').width ~= 8);
      this_block.setError('Input data type for port "i7" must have width=8.');
    end

    if (this_block.port('i8').width ~= 8);
      this_block.setError('Input data type for port "i8" must have width=8.');
    end

    if (this_block.port('i9').width ~= 8);
      this_block.setError('Input data type for port "i9" must have width=8.');
    end

    if (this_block.port('inv_en').width ~= 1);
      this_block.setError('Input data type for port "inv_en" must have width=1.');
    end

    this_block.port('inv_en').useHDLVector(false);

    if (this_block.port('noise_en').width ~= 1);
      this_block.setError('Input data type for port "noise_en" must have width=1.');
    end

    this_block.port('noise_en').useHDLVector(false);

    if (this_block.port('noise_seed').width ~= 32);
      this_block.setError('Input data type for port "noise_seed" must have width=32.');
    end

    if (this_block.port('ps_invert').width ~= 1);
      this_block.setError('Input data type for port "ps_invert" must have width=1.');
    end

    this_block.port('ps_invert').useHDLVector(false);
    
    if (this_block.port('ns_invert').width ~= 1);
      this_block.setError('Input data type for port "ns_invert" must have width=1.');
    end

    this_block.port('ns_invert').useHDLVector(false);
    
    if (this_block.port('acc_len').width ~= 32);
      this_block.setError('Input data type for port "acc_len" must have width=32.');
    end

    if (this_block.port('seed_load').width ~= 1);
      this_block.setError('Input data type for port "seed_load" must have width=1.');
    end

    this_block.port('seed_load').useHDLVector(false);

    if (this_block.port('sync').width ~= 1);
      this_block.setError('Input data type for port "sync" must have width=1.');
    end

    this_block.port('sync').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk_1','ce_1')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('adc_preproc_core.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

