
function auto_core_config(this_block)

  % Revision History:
  %
  %   22-Sep-2014  (17:23 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/jack/work/ami_correlator/ami/ami_correlator/auto_core.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('auto_core');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('acc_len');
  this_block.addSimulinkInport('noise_on');
  this_block.addSimulinkInport('sync');
  this_block.addSimulinkInport('din');

  this_block.addSimulinkOutport('dout0');
  this_block.addSimulinkOutport('dout1');
  this_block.addSimulinkOutport('dout2');
  this_block.addSimulinkOutport('dout3');
  this_block.addSimulinkOutport('dout4');
  this_block.addSimulinkOutport('dout5');
  this_block.addSimulinkOutport('dout6');
  this_block.addSimulinkOutport('dout7');
  this_block.addSimulinkOutport('vld');
  this_block.addSimulinkOutport('sync_out');


  dout0_port = this_block.port('dout0');
  dout0_port.setType('Fix_46_0');
  dout1_port = this_block.port('dout1');
  dout1_port.setType('Fix_46_0');
  dout2_port = this_block.port('dout2');
  dout2_port.setType('Fix_46_0');
  dout3_port = this_block.port('dout3');
  dout3_port.setType('Fix_46_0');
  dout4_port = this_block.port('dout4');
  dout4_port.setType('Fix_46_0');
  dout5_port = this_block.port('dout5');
  dout5_port.setType('Fix_46_0');
  dout6_port = this_block.port('dout6');
  dout6_port.setType('Fix_46_0');
  dout7_port = this_block.port('dout7');
  dout7_port.setType('Fix_46_0');
  sync_out_port = this_block.port('sync_out');
  sync_out_port.setType('Bool');
  sync_out_port.useHDLVector(false);
  vld_port = this_block.port('vld');
  vld_port.setType('Bool');
  vld_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('din').width ~= 288);
      this_block.setError('Input data type for port "din" must have width=288.');
    end

    if (this_block.port('noise_on').width ~= 1);
      this_block.setError('Input data type for port "noise_on" must have width=1.');
    end

    this_block.port('noise_on').useHDLVector(false);

    if (this_block.port('sync').width ~= 1);
      this_block.setError('Input data type for port "sync" must have width=1.');
    end

    this_block.port('sync').useHDLVector(false);
    
    if (this_block.port('acc_len').width ~= 20);
      this_block.setError('Input data type for port "acc_len" must have width=20.');
    end
  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk_1','ce_1')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('auto_core.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

