
function sb_cross_mult_core_config(this_block)

  % Revision History:
  %
  %   11-Nov-2013  (10:26 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /media/data/jack/ami/ami_correlator/sb_cross_mult_core.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('sb_cross_mult_core');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('sync_in');
  this_block.addSimulinkInport('din0');
  this_block.addSimulinkInport('din1');

  this_block.addSimulinkOutport('sync_out');
  this_block.addSimulinkOutport('dout00');
  this_block.addSimulinkOutport('dout01');
  this_block.addSimulinkOutport('dout11');

  dout00_port = this_block.port('dout00');
  dout00_port.setType('UFix_144_0');
  dout01_port = this_block.port('dout01');
  dout01_port.setType('UFix_144_0');
  dout11_port = this_block.port('dout11');
  dout11_port.setType('UFix_144_0');
  sync_out_port = this_block.port('sync_out');
  sync_out_port.setType('Bool');
  sync_out_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('din0').width ~= 64);
      this_block.setError(['Input data type for port "din0" must have width=64.','actual width is',num2str(this_block.port('din0').width)]);
    end

    if (this_block.port('din1').width ~= 64);
      this_block.setError(['Input data type for port "din1" must have width=64.','actual width is',num2str(this_block.port('din1').width)]);
    end

    if (this_block.port('sync_in').width ~= 1);
      this_block.setError(['Input data type for port "sync_in" must have width=1.','actual width is',num2str(this_block.port('sync_in').width)]);

    end

    this_block.port('sync_in').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk_1','ce_1')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('sb_cross_mult_core.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

