
function tge_rx_8a_core_config(this_block)

  % Revision History:
  %
  %   06-Jan-2015  (18:02 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/jack/work/ami_correlator/ami/ami_correlator/tge_rx_8a_core.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('tge_rx_8a_core');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('ant_id');
  this_block.addSimulinkInport('gbe_din');
  this_block.addSimulinkInport('gbe_eof');
  this_block.addSimulinkInport('gbe_vld');
  this_block.addSimulinkInport('lb_din');
  this_block.addSimulinkInport('lb_eof');
  this_block.addSimulinkInport('lb_vld');
  this_block.addSimulinkInport('rd_addr');
  this_block.addSimulinkInport('rd_en');

  this_block.addSimulinkOutport('dout');
  this_block.addSimulinkOutport('lb_bad_addr');
  this_block.addSimulinkOutport('lb_err');
  this_block.addSimulinkOutport('lb_pkt_err');
  this_block.addSimulinkOutport('lb_order_err');

  this_block.addSimulinkOutport('max_buf');
  this_block.addSimulinkOutport('mcnt_out');
  this_block.addSimulinkOutport('sync_out');
  this_block.addSimulinkOutport('tge_bad_addr');
  this_block.addSimulinkOutport('tge_err');
  this_block.addSimulinkOutport('tge_pkt_err');
  this_block.addSimulinkOutport('tge_order_err');

  this_block.addSimulinkOutport('vld_out');

  dout_port = this_block.port('dout');
  dout_port.setType('UFix_128_0');
  lb_bad_addr_port = this_block.port('lb_bad_addr');
  lb_bad_addr_port.setType('UFix_13_0');
  lb_err_port = this_block.port('lb_err');
  lb_err_port.setType('Bool');
  lb_err_port.useHDLVector(false);
  lb_pkt_err_port = this_block.port('lb_pkt_err');
  lb_pkt_err_port.setType('Bool');
  lb_pkt_err_port.useHDLVector(false);
  lb_order_err_port = this_block.port('lb_order_err');
  lb_order_err_port.setType('Bool');
  lb_order_err_port.useHDLVector(false);
  max_buf_port = this_block.port('max_buf');
  max_buf_port.setType('UFix_7_0');
  mcnt_out_port = this_block.port('mcnt_out');
  mcnt_out_port.setType('UFix_48_0');
  sync_out_port = this_block.port('sync_out');
  sync_out_port.setType('Bool');
  sync_out_port.useHDLVector(false);
  tge_bad_addr_port = this_block.port('tge_bad_addr');
  tge_bad_addr_port.setType('UFix_13_0');
  tge_err_port = this_block.port('tge_err');
  tge_err_port.setType('Bool');
  tge_err_port.useHDLVector(false);
  tge_pkt_err_port = this_block.port('tge_pkt_err');
  tge_pkt_err_port.setType('Bool');
  tge_pkt_err_port.useHDLVector(false);
  tge_order_err_port = this_block.port('tge_order_err');
  tge_order_err_port.setType('Bool');
  tge_order_err_port.useHDLVector(false);
  vld_out_port = this_block.port('vld_out');
  vld_out_port.setType('Bool');
  vld_out_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('ant_id').width ~= 4);
      this_block.setError('Input data type for port "ant_id" must have width=4.');
    end

    if (this_block.port('gbe_din').width ~= 64);
      this_block.setError('Input data type for port "gbe_din" must have width=64.');
    end

    if (this_block.port('gbe_eof').width ~= 1);
      this_block.setError('Input data type for port "gbe_eof" must have width=1.');
    end

    this_block.port('gbe_eof').useHDLVector(false);

    if (this_block.port('gbe_vld').width ~= 1);
      this_block.setError('Input data type for port "gbe_vld" must have width=1.');
    end

    this_block.port('gbe_vld').useHDLVector(false);

    if (this_block.port('lb_din').width ~= 64);
      this_block.setError('Input data type for port "lb_din" must have width=64.');
    end

    if (this_block.port('lb_eof').width ~= 1);
      this_block.setError('Input data type for port "lb_eof" must have width=1.');
    end

    this_block.port('lb_eof').useHDLVector(false);

    if (this_block.port('lb_vld').width ~= 1);
      this_block.setError('Input data type for port "lb_vld" must have width=1.');
    end

    this_block.port('lb_vld').useHDLVector(false);

    if (this_block.port('rd_addr').width ~= 13);
      this_block.setError('Input data type for port "rd_addr" must have width=13.');
    end

    if (this_block.port('rd_en').width ~= 1);
      this_block.setError('Input data type for port "rd_en" must have width=1.');
    end

    this_block.port('rd_en').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk_1','ce_1')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('tge_rx_8a_core.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

